version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/urs/src/app/src
      - ./nodemon.json:/urs/src/app/nodemon.json
    container_name: ts-node-docker
    command: npm run dev
